version: 0.2
phases:
  install:
    runtime-versions:
      docker: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=$ID_AWS_ACCOUNT_ECR.dkr.ecr.us-east-1.amazonaws.com/$APPNAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $REPOSITORY_URI
      - echo $APPNAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest --build-arg ID_AWS_ACCOUNT_ECR=$ID_AWS_ACCOUNT_ECR --build-arg REPO_TOKEN=$REPO_TOKEN  --build-arg APPNAME=$APPNAME  --build-arg RESTPORT=80  --build-arg GOOS=linux --build-arg GOARCH=amd64 --build-arg GOPRIVATE="" .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name”:"${APPNAME}","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
