version: 0.2
phases:
  pre_build:
    commands:
      - git --version
      - git settings --global user.email "quirama80@gmail.com"
      - git settings --global user.name "🔥AWS-PIPELINE - $APPNAME"
      - git settings --global user.username "jhonquirama"
      - git settings --global
        url."https://jhonquirama:$GH_TOKEN@github.com/jhonquirama/".insteadOf
        "https://github.com/jhonquirama/"
      - sudo wget
        https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64
        -O /usr/bin/yq
      - sudo chmod +x /usr/bin/yq
      - yq --version
      - git clone -b
        $BRANCH_REPO_EKS  https://github.com/jhonquirama/blt-msa-infra-eks.git

      - curl -fsSL -o get_helm.sh
        https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - helm version
  build:
    commands:
      - COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      - BRANCH="AWS-PIPELINE/update_image_$COMMIT_HASH"
      - export GITHUB_TOKEN=
      - echo "---------------------------"
      - echo $COMMIT_HASH
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - cd blt-msa-infra-eks/apps
      - REPOSITORY_URI=240415772733.dkr.ecr.us-east-1.amazonaws.com/$APPNAME
      - TAG=$IMAGE_TAG
      - yq -i '.description = "'$TAG'"' $APPNAME/Chart.yaml
      - yq -i '.image.tag = "'$TAG'"' $APPNAME/values.yaml
      - helm lint $APPNAME
      # - git checkout -b $BRANCH
      - git add .
      - git commit -m "AWS-PIPELINE automatic update - COMMIT  - $COMMIT_HASH"
      - git push origin $BRANCH_REPO_EKS