// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jhonquirama/my-portfolio/internal/portfolio/business/model"
	mock "github.com/stretchr/testify/mock"
)

// PortfolioService is an autogenerated mock type for the PortfolioService type
type PortfolioService struct {
	mock.Mock
}

// GetHealth provides a mock function with given fields: ctx, filter
func (_m *PortfolioService) GetHealth(ctx context.Context, filter model.GetHealth) (model.Health, error) {
	ret := _m.Called(ctx, filter)

	var r0 model.Health
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetHealth) (model.Health, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetHealth) model.Health); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(model.Health)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetHealth) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPortfolioService creates a new instance of PortfolioService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioService {
	mock := &PortfolioService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
