// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jhonquirama/my-portfolio/internal/users/business/model"
	mock "github.com/stretchr/testify/mock"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// UsersConfirmSignUp provides a mock function with given fields: ctx, data
func (_m *UsersService) UsersConfirmSignUp(ctx context.Context, data model.UsersConfirmSignUpInputAndSignInInput) (model.UsersSignInOutput, error) {
	ret := _m.Called(ctx, data)

	var r0 model.UsersSignInOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersConfirmSignUpInputAndSignInInput) (model.UsersSignInOutput, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersConfirmSignUpInputAndSignInInput) model.UsersSignInOutput); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(model.UsersSignInOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UsersConfirmSignUpInputAndSignInInput) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersInitiateAuth provides a mock function with given fields: ctx, user
func (_m *UsersService) UsersInitiateAuth(ctx context.Context, user model.UsersSignUpAndSignInInput) (model.UsersSignInOutput, error) {
	ret := _m.Called(ctx, user)

	var r0 model.UsersSignInOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpAndSignInInput) (model.UsersSignInOutput, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpAndSignInInput) model.UsersSignInOutput); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(model.UsersSignInOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UsersSignUpAndSignInInput) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersSignUp provides a mock function with given fields: ctx, data
func (_m *UsersService) UsersSignUp(ctx context.Context, data model.UsersSignUpAndSignInInput) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpAndSignInInput) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUsersService creates a new instance of UsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersService {
	mock := &UsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
