// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	oteltrace "go.opentelemetry.io/otel/trace"

	trace "go.opentelemetry.io/otel/sdk/trace"
)

// TelemetryProvider is an autogenerated mock type for the TelemetryProvider type
type TelemetryProvider struct {
	mock.Mock
}

// GetProvider provides a mock function with given fields:
func (_m *TelemetryProvider) GetProvider() *trace.TracerProvider {
	ret := _m.Called()

	var r0 *trace.TracerProvider
	if rf, ok := ret.Get(0).(func() *trace.TracerProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trace.TracerProvider)
		}
	}

	return r0
}

// GetServiceName provides a mock function with given fields:
func (_m *TelemetryProvider) GetServiceName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Shutdown provides a mock function with given fields: ctx
func (_m *TelemetryProvider) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}

// TraceStart provides a mock function with given fields: ctx, name
func (_m *TelemetryProvider) TraceStart(ctx context.Context, name string) (context.Context, oteltrace.Span) {
	ret := _m.Called(ctx, name)

	var r0 context.Context
	var r1 oteltrace.Span
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, oteltrace.Span)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) oteltrace.Span); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(oteltrace.Span)
		}
	}

	return r0, r1
}

// NewTelemetryProvider creates a new instance of TelemetryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelemetryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelemetryProvider {
	mock := &TelemetryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
