// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dynamodb "github.com/jhonquirama/my-portfolio/pkg/data/dynamodb"
	mock "github.com/stretchr/testify/mock"

	model "github.com/jhonquirama/my-portfolio/pkg/data/dynamodb/model"
)

// Dynamodb is an autogenerated mock type for the Dynamodb type
type Dynamodb struct {
	mock.Mock
}

// BatchGetItemAll provides a mock function with given fields: ctx, tableName, keyConditions, result
func (_m *Dynamodb) BatchGetItemAll(ctx context.Context, tableName string, keyConditions []dynamodb.ConditionalValues, result interface{}) error {
	ret := _m.Called(ctx, tableName, keyConditions, result)

	if len(ret) == 0 {
		panic("no return value specified for BatchGetItemAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []dynamodb.ConditionalValues, interface{}) error); ok {
		r0 = rf(ctx, tableName, keyConditions, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BatchGetItemAllCall provides a mock function with given fields: ctx, filter, result
func (_m *Dynamodb) BatchGetItemAllCall(ctx context.Context, filter model.BatchGetItemInputCall, result interface{}) error {
	ret := _m.Called(ctx, filter, result)

	if len(ret) == 0 {
		panic("no return value specified for BatchGetItemAllCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BatchGetItemInputCall, interface{}) error); ok {
		r0 = rf(ctx, filter, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteItem provides a mock function with given fields: ctx, tableName, filter
func (_m *Dynamodb) DeleteItem(ctx context.Context, tableName string, filter dynamodb.ConditionalValues) error {
	ret := _m.Called(ctx, tableName, filter)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dynamodb.ConditionalValues) error); ok {
		r0 = rf(ctx, tableName, filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetItem provides a mock function with given fields: ctx, tableName, keyCondition, result
func (_m *Dynamodb) GetItem(ctx context.Context, tableName string, keyCondition dynamodb.ConditionalValues, result interface{}) error {
	ret := _m.Called(ctx, tableName, keyCondition, result)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dynamodb.ConditionalValues, interface{}) error); ok {
		r0 = rf(ctx, tableName, keyCondition, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetItemCall provides a mock function with given fields: ctx, tableName, filter, result
func (_m *Dynamodb) GetItemCall(ctx context.Context, tableName string, filter model.GetItemInputCall, result interface{}) error {
	ret := _m.Called(ctx, tableName, filter, result)

	if len(ret) == 0 {
		panic("no return value specified for GetItemCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.GetItemInputCall, interface{}) error); ok {
		r0 = rf(ctx, tableName, filter, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutItem provides a mock function with given fields: ctx, tableName, item
func (_m *Dynamodb) PutItem(ctx context.Context, tableName string, item interface{}) error {
	ret := _m.Called(ctx, tableName, item)

	if len(ret) == 0 {
		panic("no return value specified for PutItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, tableName, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Query provides a mock function with given fields: ctx, tableName, keyCondition, filter, result, pagination, options
func (_m *Dynamodb) Query(ctx context.Context, tableName string, keyCondition dynamodb.ConditionalValues, filter dynamodb.ConditionalValues, result interface{}, pagination interface{}, options ...dynamodb.QueryOptions) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tableName, keyCondition, filter, result, pagination)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dynamodb.ConditionalValues, dynamodb.ConditionalValues, interface{}, interface{}, ...dynamodb.QueryOptions) error); ok {
		r0 = rf(ctx, tableName, keyCondition, filter, result, pagination, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryAll provides a mock function with given fields: ctx, tableName, keyCondition, filter, result, pagination, limitTotal, options
func (_m *Dynamodb) QueryAll(ctx context.Context, tableName string, keyCondition dynamodb.ConditionalValues, filter dynamodb.ConditionalValues, result interface{}, pagination interface{}, limitTotal int32, options ...dynamodb.QueryOptions) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tableName, keyCondition, filter, result, pagination, limitTotal)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dynamodb.ConditionalValues, dynamodb.ConditionalValues, interface{}, interface{}, int32, ...dynamodb.QueryOptions) error); ok {
		r0 = rf(ctx, tableName, keyCondition, filter, result, pagination, limitTotal, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryAllCall provides a mock function with given fields: ctx, tableName, filter, result, pagination, iterations, options
func (_m *Dynamodb) QueryAllCall(ctx context.Context, tableName string, filter model.QueryAllInputCall, result interface{}, pagination interface{}, iterations int32, options ...dynamodb.QueryOptions) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tableName, filter, result, pagination, iterations)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryAllCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.QueryAllInputCall, interface{}, interface{}, int32, ...dynamodb.QueryOptions) error); ok {
		r0 = rf(ctx, tableName, filter, result, pagination, iterations, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactWriteItems provides a mock function with given fields: ctx, data
func (_m *Dynamodb) TransactWriteItems(ctx context.Context, data dynamodb.TransactWriteItems) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for TransactWriteItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dynamodb.TransactWriteItems) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactWriteItemsCall provides a mock function with given fields: ctx, input
func (_m *Dynamodb) TransactWriteItemsCall(ctx context.Context, input model.TransactWriteItemsInputCall) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for TransactWriteItemsCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TransactWriteItemsInputCall) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateItem provides a mock function with given fields: ctx, tableName, input
func (_m *Dynamodb) UpdateItem(ctx context.Context, tableName string, input model.UpdateItemInput) error {
	ret := _m.Called(ctx, tableName, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateItemInput) error); ok {
		r0 = rf(ctx, tableName, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithLimit provides a mock function with given fields: limit
func (_m *Dynamodb) WithLimit(limit *int32) dynamodb.QueryOptions {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for WithLimit")
	}

	var r0 dynamodb.QueryOptions
	if rf, ok := ret.Get(0).(func(*int32) dynamodb.QueryOptions); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamodb.QueryOptions)
		}
	}

	return r0
}

// WithPagination provides a mock function with given fields: pagination
func (_m *Dynamodb) WithPagination(pagination map[string]interface{}) dynamodb.QueryOptions {
	ret := _m.Called(pagination)

	if len(ret) == 0 {
		panic("no return value specified for WithPagination")
	}

	var r0 dynamodb.QueryOptions
	if rf, ok := ret.Get(0).(func(map[string]interface{}) dynamodb.QueryOptions); ok {
		r0 = rf(pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamodb.QueryOptions)
		}
	}

	return r0
}

// WithQueryIndex provides a mock function with given fields: indexName
func (_m *Dynamodb) WithQueryIndex(indexName *string) dynamodb.QueryOptions {
	ret := _m.Called(indexName)

	if len(ret) == 0 {
		panic("no return value specified for WithQueryIndex")
	}

	var r0 dynamodb.QueryOptions
	if rf, ok := ret.Get(0).(func(*string) dynamodb.QueryOptions); ok {
		r0 = rf(indexName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamodb.QueryOptions)
		}
	}

	return r0
}

// NewDynamodb creates a new instance of Dynamodb. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamodb(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dynamodb {
	mock := &Dynamodb{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
