// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// QueryOptions is an autogenerated mock type for the QueryOptions type
type QueryOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: input
func (_m *QueryOptions) Execute(input *dynamodb.QueryInput) {
	_m.Called(input)
}

// NewQueryOptions creates a new instance of QueryOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryOptions {
	mock := &QueryOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
