// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jhonquirama/my-portfolio/internal/health/business/model"
	mock "github.com/stretchr/testify/mock"
)

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

// GetHealth provides a mock function with given fields: ctx, filter
func (_m *HealthService) GetHealth(ctx context.Context, filter model.GetHealth) (model.Health, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 model.Health
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetHealth) (model.Health, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetHealth) model.Health); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(model.Health)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetHealth) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
