// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jhonquirama/my-portfolio/internal/users/business/model"
	mock "github.com/stretchr/testify/mock"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// UsersConfirmSignUp provides a mock function with given fields: ctx, data
func (_m *UsersService) UsersConfirmSignUp(ctx context.Context, data model.UsersConfirmSignUpInput) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersConfirmSignUpInput) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersSignUp provides a mock function with given fields: ctx, data
func (_m *UsersService) UsersSignUp(ctx context.Context, data model.UsersSignUpInput) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpInput) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUsersService creates a new instance of UsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersService {
	mock := &UsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
