// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jhonquirama/my-portfolio/internal/users/business/model"
	mock "github.com/stretchr/testify/mock"
)

// CognitoClientAuthRepository is an autogenerated mock type for the CognitoClientAuthRepository type
type CognitoClientAuthRepository struct {
	mock.Mock
}

// ConfirmSignUp provides a mock function with given fields: ctx, data
func (_m *CognitoClientAuthRepository) ConfirmSignUp(ctx context.Context, data model.UsersConfirmSignUpInputAndSignInInput) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersConfirmSignUpInputAndSignInInput) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SignUp provides a mock function with given fields: ctx, data
func (_m *CognitoClientAuthRepository) SignUp(ctx context.Context, data model.UsersSignUpAndSignInInput) (model.UsersSignUpOutput, error) {
	ret := _m.Called(ctx, data)

	var r0 model.UsersSignUpOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpAndSignInInput) (model.UsersSignUpOutput, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpAndSignInInput) model.UsersSignUpOutput); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(model.UsersSignUpOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UsersSignUpAndSignInInput) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersInitiateAuth provides a mock function with given fields: ctx, data
func (_m *CognitoClientAuthRepository) UsersInitiateAuth(ctx context.Context, data model.UsersSignUpAndSignInInput) (model.UsersSignInOutput, error) {
	ret := _m.Called(ctx, data)

	var r0 model.UsersSignInOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpAndSignInInput) (model.UsersSignInOutput, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UsersSignUpAndSignInInput) model.UsersSignInOutput); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(model.UsersSignInOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UsersSignUpAndSignInInput) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCognitoClientAuthRepository creates a new instance of CognitoClientAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCognitoClientAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CognitoClientAuthRepository {
	mock := &CognitoClientAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
