// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DBAuthRepository is an autogenerated mock type for the DBAuthRepository type
type DBAuthRepository struct {
	mock.Mock
}

// NewDBAuthRepository creates a new instance of DBAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBAuthRepository {
	mock := &DBAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
