#!/usr/bin/env bash 

set -o errexit
set -o nounset

if [ -z "${APPNAME}" ]; then
    echo "APPNAME must be set"
    exit 1
fi

if [ -z "${GOARCH}" ]; then
    echo "Using default GOARCH"
else
    echo "Using GOARCH=${GOARCH}"
fi

if [ -z "${GOOS}" ]; then
    echo "Using default GOOS"
else
    echo "Using GOOS=${GOOS}"
fi

export CGO_ENABLED=1

echo "Go building app"
# shellcheck disable=SC2016
go build -tags musl -ldflags '-extldflags "-static" -linkmode external -w -s -X main.Version=${VERSION}' -o build/${APPNAME} ./cmd/main.go
echo "Successfully built, exiting build script"