// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HealthRepository is an autogenerated mock type for the HealthRepository type
type HealthRepository struct {
	mock.Mock
}

// NewHealthRepository creates a new instance of HealthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthRepository {
	mock := &HealthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
