// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jhonquirama/my-portfolio/pkg/cloud/aws/cognito/model"
	mock "github.com/stretchr/testify/mock"
)

// Cognito is an autogenerated mock type for the Cognito type
type Cognito struct {
	mock.Mock
}

// ConfirmSignUp provides a mock function with given fields: ctx, input
func (_m *Cognito) ConfirmSignUp(ctx context.Context, input model.ConfirmSignUpInput) (model.ConfirmSignUpOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 model.ConfirmSignUpOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ConfirmSignUpInput) (model.ConfirmSignUpOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ConfirmSignUpInput) model.ConfirmSignUpOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.ConfirmSignUpOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ConfirmSignUpInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignIn provides a mock function with given fields: ctx, input
func (_m *Cognito) SignIn(ctx context.Context, input model.InitiateAuthInput) (model.InitiateAuthOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 model.InitiateAuthOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.InitiateAuthInput) (model.InitiateAuthOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.InitiateAuthInput) model.InitiateAuthOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.InitiateAuthOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.InitiateAuthInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignUp provides a mock function with given fields: ctx, input
func (_m *Cognito) SignUp(ctx context.Context, input model.SignUpInput) (model.SignUpOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 model.SignUpOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SignUpInput) (model.SignUpOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SignUpInput) model.SignUpOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.SignUpOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SignUpInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCognito creates a new instance of Cognito. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCognito(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cognito {
	mock := &Cognito{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
