// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	postgresql "github.com/jhonquirama/my-portfolio/pkg/data/postgresql"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// Array provides a mock function with given fields: array
func (_m *DB) Array(array interface{}) postgresql.AnyArray {
	ret := _m.Called(array)

	var r0 postgresql.AnyArray
	if rf, ok := ret.Get(0).(func(interface{}) postgresql.AnyArray); ok {
		r0 = rf(array)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(postgresql.AnyArray)
		}
	}

	return r0
}

// Close provides a mock function with given fields: rows
func (_m *DB) Close(rows postgresql.SQLRows) {
	_m.Called(rows)
}

// DoTransactionWithContext provides a mock function with given fields: ctx, fnStmt
func (_m *DB) DoTransactionWithContext(ctx context.Context, fnStmt postgresql.ExecStmt) error {
	ret := _m.Called(ctx, fnStmt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgresql.ExecStmt) error); ok {
		r0 = rf(ctx, fnStmt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *DB) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PingContext provides a mock function with given fields: _a0
func (_m *DB) PingContext(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *DB) QueryContext(ctx context.Context, query string, args ...interface{}) (postgresql.SQLRows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 postgresql.SQLRows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (postgresql.SQLRows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) postgresql.SQLRows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(postgresql.SQLRows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDB interface {
	mock.TestingT
	Cleanup(func())
}

// NewDB creates a new instance of DB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDB(t mockConstructorTestingTNewDB) *DB {
	mock := &DB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
