name: test-lint-build-deploy

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - '**.txt'
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Branch to deploy (e.g., feature-x)'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/jhonquirama/config
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      RESTPORT: 8080
      ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      APP_NAME: "blt-msa-ha-checkout-bookings-broker"

    steps:
      - name: Configure Git
        run: git config --global url.https://${{ env.REPO_TOKEN }}@github.com/jhonquirama/.insteadOf https://github.com/jhonquirama/

      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Build
        run: make build

      - name: Lint
        run: |
          export GO111MODULE=off
          make lint

      - name: Unit tests
        run: |
          go test -tags musl ./internal/... -coverprofile coverage.out -covermode count
          go tool cover -func coverage.out

      - name: Quality Gate
        run: make coverage

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        id: docker_push
        run: |
          RAW_TAG=${{ github.event.inputs.target-branch || github.ref_name }}
          TAG=$(echo "$RAW_TAG" | tr '/' '-' | cut -c 1-30)
          echo "Normalized tag: $TAG"
          
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$TAG .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$TAG
          
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "IMAGE=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$TAG" >> $GITHUB_ENV

      - name: Update Helm Chart
        if: success()
        env:
          INFRA_REPO: "infra-core"
          INFRA_REPO_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}
        run: |
          echo "Using tag: $TAG"
          
          git clone https://$INFRA_REPO_TOKEN@github.com/jhonquirama/$INFRA_REPO.git
          cd $INFRA_REPO
          
          mkdir -p kubernetes/${{ env.APP_NAME }}
          cat <<EOF > kubernetes/${{ env.APP_NAME }}/values.yaml
          image:
            repository: ${IMAGE%%:*}
            tag: "$TAG"
            EOF
            
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add .
            git commit -m "Deploy $TAG"
            git push
