name: test-lint-build-deploy

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Branch to deploy (e.g., feature-x)'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/jhonquirama/config
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      RESTPORT: 8080
      ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      APP_NAME: "blt-msa-ha-checkout-bookings-broker"  # Nombre de tu app

    steps:
      # Configuración inicial de Git y Go
      - run: git config --global url.https://$REPO_TOKEN@github.com/jhonquirama/.insteadOf https://github.com/jhonquirama/
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      # Build, tests y linting
      - name: Build
        run: make build

      - name: Lint
        run: |
          export GO111MODULE=off
          make lint

      - name: Unit tests
        run: |
          go test -tags musl ./internal/... -coverprofile coverage.out -covermode count
          go tool cover -func coverage.out

      - name: Quality Gate - Test coverage
        run: make coverage

      # Autenticación en AWS ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # Versión más reciente
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Construir y subir imagen Docker
      - name: Build and Push Docker image
        id: docker_push
        env:
          ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          # Normalizar el tag
          RAW_TAG=${{ github.event.inputs.target-branch || github.ref_name }}
          TAG=$(echo "$RAW_TAG" | tr '/' '-' | cut -c 1-30)
          echo "Normalized tag: $TAG"

          # Construir y subir imagen
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG

          # Guardar tag para pasos posteriores
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$TAG" >> $GITHUB_ENV

      - name: Update Helm Chart
        if: success()
        env:
          INFRA_REPO: "infra-core"
        run: |
          echo "Using normalized tag: ${{ env.TAG }}"

          # Clonar repo de infraestructura
          git clone https://${{ secrets.INFRA_REPO_TOKEN }}@github.com/jhonquirama/$INFRA_REPO.git
          cd $INFRA_REPO

          # Actualizar values.yaml
          cat <<EOF > kubernetes/${{ env.APP_NAME }}/values.yaml
          image:
            repository: ${{ env.IMAGE%%:*}}
            tag: "${{ env.TAG }}"
          EOF

          # Hacer commit y push
          git config user.email "quirama80@gmail.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Auto-update: Deploy ${{ env.TAG }}"
          git push


      # ----------- Docker Hub (Opcional - Comentado) -----------
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and Push to Docker Hub
      #   run: |
      #     IMAGE_TAG=develop
      #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myservice:$IMAGE_TAG .
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/myservice:$IMAGE_TAG
