name: 📦🚀 CI/CD Caller 📞
on:
    workflow_dispatch:
    pull_request:
    push:
      branches:
        - develop
        - master
      paths-ignore:
        - .github/workflows/**
        - .gitignore
        - README.md
        - readme.md
        - CHANGELOG.md
permissions:
    id-token: write
    contents: read
jobs:
    ContinuousIntegration:
      if: ${{ github.event_name != 'pull_request' }}
      uses: jhonquirama/blt-do-matrix/.github/workflows/CI.yaml@master
      with:
        aws-region: us-east-1
        app-name: hexagonal-scaffolding
      secrets: inherit

    Tests:
      uses: jhonquirama/blt-do-matrix/.github/workflows/tests.yaml@master
      with:
        test-coverage-threshold: 59
        unit-tests: true
      secrets: inherit

    ContinuousDeployment:
      needs: [ContinuousIntegration, Tests]
      uses: jhonquirama/blt-do-matrix/.github/workflows/CD.yaml@master
      with:
        aws-region: us-east-1
        app-name: hexagonal-scaffolding
        project: scaffonding
      secrets: inherit