name: 🚀 Release Caller 📞
on:
    push:
      branches:
        - master
      paths-ignore:
        - .github/workflows/**
        - .gitignore
permissions:
    pull-requests: write
    contents: write
jobs:
    GenerateRelease:
      uses: jhonquirama/blt-do-matrix/.github/workflows/release.yaml@master
      secrets: inherit