name: 🌎 Terraform Apply Caller 📞
on: 
    push:
      branches:
        - develop
        - master
        - qa
      paths:
        - iac/**

permissions:
    id-token: write
    contents: read
jobs:
    TerraformApply:
      uses: jhonquirama/blt-do-matrix/.github/workflows/apply.yaml@master
      with:
        aws-region: us-east-1
        use-vpn: false
      secrets: inherit