name: 🌎 Terraform Plan Caller 📞
on: 
    pull_request:
      branches:
        - develop
        - master
        - qa
      paths:
        - iac/**
        
permissions:
    id-token: write
    contents: read
jobs:
    TerraformPlan:
      uses: jhonquirama/blt-do-matrix/.github/workflows/plan.yaml@master
      with:
        aws-region: us-east-1
        use-vpn: false
      secrets: inherit
